### ISSUE TITLE
Geochat is not working

### ISSUE THREAD

**Issue by acamat** [Zverik/geochat#2]
When you try to log in to geochat is displays a message:

Failed to log in to GeoChat:
Failed to get messages as *****:
Database query for messages failed: FUNCTION iodb.X does not exist

Can you fix this, because GeoChat is a great plugin for JOSM

**Comment by Zverik** [comment]
Fixed in 218ec18c0958ffcea7f814c444de425e9bff07d5, thanks for reporting!
